import type { PipelineConfig } from './types';

export const PIPELINES: PipelineConfig[] = [
  {
    slug: 'github-trends',
    name: 'GitHub Trends Daily Digest',
    icon: 'GitBranch',
    description:
      'Automatically fetches trending GitHub repositories daily, scores them by relevance, and generates ready-to-publish LinkedIn posts about the most interesting AI projects.',
    automationLevel: 'high',
    outputVolume: '1 post/day',
    schedule: '0 8 * * *',
    pillarSlugs: ['breaking-ai-news'],
    steps: [
      {
        id: 'github-trends-ingest',
        name: 'Fetch GitHub Trending',
        type: 'ingest',
        description: 'Fetch trending repositories from GitHub filtered by AI/ML topics',
        automated: true,
      },
      {
        id: 'github-trends-filter',
        name: 'Score by Stars & Language',
        type: 'filter',
        description: 'Score and rank repos by star velocity, language, and AI relevance',
        automated: true,
      },
      {
        id: 'github-trends-generate',
        name: 'Claude Drafts Post',
        type: 'generate',
        description: 'Use Claude to draft an engaging LinkedIn post about the top trending repo',
        automated: true,
      },
      {
        id: 'github-trends-review',
        name: 'Human Approval',
        type: 'review',
        description: 'Review the generated post and approve, edit, or reject',
        automated: false,
      },
      {
        id: 'github-trends-publish',
        name: 'Schedule to LinkedIn',
        type: 'publish',
        description: 'Schedule the approved post to LinkedIn via Buffer',
        automated: true,
      },
    ],
    keyTools: ['GitHub API', 'Claude', 'Buffer'],
    color: 'blue',
  },
  {
    slug: 'signal-amplifier',
    name: 'Signal Amplifier',
    icon: 'Radio',
    description:
      'Monitors key Twitter/X accounts and AI communities for high-signal posts, then generates upgraded reshares with added context and analysis.',
    automationLevel: 'high',
    outputVolume: '2-3 posts/day',
    schedule: '0 */3 * * *',
    pillarSlugs: ['reshared-posts'],
    steps: [
      {
        id: 'signal-ingest',
        name: 'Monitor Twitter Accounts',
        type: 'ingest',
        description: 'Monitor curated list of AI thought leaders and communities on Twitter/X',
        automated: true,
      },
      {
        id: 'signal-filter',
        name: 'Engagement Threshold',
        type: 'filter',
        description: 'Filter posts by engagement metrics and relevance scoring',
        automated: true,
      },
      {
        id: 'signal-generate',
        name: 'Add Context via Claude',
        type: 'generate',
        description: 'Generate an upgraded reshare with unique perspective and added context',
        automated: true,
      },
      {
        id: 'signal-review',
        name: 'Quick Approve',
        type: 'review',
        description: 'Quick review via Telegram bot for fast approval',
        automated: false,
      },
      {
        id: 'signal-publish',
        name: 'LinkedIn + Instagram',
        type: 'publish',
        description: 'Publish to LinkedIn and Instagram simultaneously',
        automated: true,
      },
    ],
    keyTools: ['Twitter API', 'Claude', 'Telegram Bot', 'Buffer'],
    color: 'violet',
  },
  {
    slug: 'release-radar',
    name: 'AI Company Release Radar',
    icon: 'Radar',
    description:
      'Tracks AI company releases via RSS feeds and HackerNews, turning changelogs and announcements into compelling story-driven content.',
    automationLevel: 'medium',
    outputVolume: 'On-demand',
    pillarSlugs: ['breaking-ai-news'],
    steps: [
      {
        id: 'release-ingest',
        name: 'RSS + HackerNews',
        type: 'ingest',
        description: 'Monitor RSS feeds from major AI companies and HackerNews front page',
        automated: true,
      },
      {
        id: 'release-filter',
        name: 'Score > 200 + AI Tag',
        type: 'filter',
        description: 'Filter for posts with score > 200 and AI/ML relevance tags',
        automated: true,
      },
      {
        id: 'release-generate',
        name: 'Changelog to Story',
        type: 'generate',
        description: 'Transform dry changelogs and release notes into engaging narratives',
        automated: true,
      },
      {
        id: 'release-review',
        name: 'Edit & Approve',
        type: 'review',
        description: 'Human review to ensure accuracy and add personal insights',
        automated: false,
      },
      {
        id: 'release-publish',
        name: 'Multi-platform',
        type: 'publish',
        description: 'Publish across LinkedIn, Twitter, and YouTube community posts',
        automated: true,
      },
    ],
    keyTools: ['RSS Parser', 'HackerNews API', 'Claude', 'Buffer'],
    color: 'amber',
  },
  {
    slug: 'youtube-series',
    name: 'YouTube Built in 24h',
    icon: 'Video',
    description:
      'Generates script outlines for weekly YouTube videos featuring live builds and demos of trending AI tools, from concept to published video.',
    automationLevel: 'low',
    outputVolume: '1 video/week',
    pillarSlugs: ['live-demos'],
    steps: [
      {
        id: 'youtube-ingest',
        name: 'ArXiv + Trending Tools',
        type: 'ingest',
        description: 'Scan ArXiv papers and trending AI tools for video topics',
        automated: true,
      },
      {
        id: 'youtube-generate',
        name: 'Script Outline',
        type: 'generate',
        description: 'Generate a detailed script outline with hooks, segments, and CTAs',
        automated: true,
      },
      {
        id: 'youtube-review',
        name: 'Full Creative Review',
        type: 'review',
        description: 'Full creative review of script, thumbnail concepts, and production plan',
        automated: false,
      },
    ],
    keyTools: ['ArXiv API', 'Claude', 'YouTube Studio'],
    color: 'emerald',
  },
  {
    slug: 'weekly-strategy',
    name: 'Weekly Strategy Breakdown',
    icon: 'Target',
    description:
      'Pulls data from EDGAR filings, LinkedIn job trends, and industry reports to create deep-dive strategy posts every Monday morning.',
    automationLevel: 'medium',
    outputVolume: '1 post/week',
    schedule: '0 8 * * 1',
    pillarSlugs: ['strategy-career', 'inside-the-machine'],
    steps: [
      {
        id: 'strategy-ingest',
        name: 'EDGAR + LinkedIn Jobs + Reports',
        type: 'ingest',
        description: 'Gather data from SEC EDGAR filings, LinkedIn job postings, and industry reports',
        automated: true,
      },
      {
        id: 'strategy-filter',
        name: 'Relevance Scoring',
        type: 'filter',
        description: 'Score and rank findings by strategic relevance and timeliness',
        automated: true,
      },
      {
        id: 'strategy-generate',
        name: 'Deep Dive Draft',
        type: 'generate',
        description: 'Generate a comprehensive strategy breakdown with data-backed insights',
        automated: true,
      },
      {
        id: 'strategy-review',
        name: 'Edit & Polish',
        type: 'review',
        description: 'Human review to refine analysis and add personal strategic perspective',
        automated: false,
      },
      {
        id: 'strategy-publish',
        name: 'LinkedIn',
        type: 'publish',
        description: 'Publish the strategy post to LinkedIn with optimal Monday morning timing',
        automated: true,
      },
    ],
    keyTools: ['EDGAR API', 'LinkedIn API', 'Claude'],
    color: 'red',
  },
  {
    slug: 'auto-podcast',
    name: 'Auto-Podcast Engine',
    icon: 'Mic',
    description:
      'Generates podcast scripts from the week\'s best content, produces audio with AI voices, cuts highlight clips, and publishes to podcast platforms.',
    automationLevel: 'high',
    outputVolume: '1 ep + 3 clips/week',
    schedule: '0 10 * * 3',
    pillarSlugs: ['hype-detector', 'breaking-ai-news'],
    steps: [
      {
        id: 'podcast-generate',
        name: 'Script from Content',
        type: 'generate',
        description: 'Generate a conversational podcast script from the week\'s top content pieces',
        automated: true,
      },
      {
        id: 'podcast-audio',
        name: 'ElevenLabs Voices',
        type: 'audio_video',
        description: 'Generate podcast audio using ElevenLabs AI voices',
        automated: true,
      },
      {
        id: 'podcast-clips',
        name: 'Cut Clips',
        type: 'audio_video',
        description: 'Automatically identify and cut 3 highlight clips for social media',
        automated: true,
      },
      {
        id: 'podcast-review',
        name: 'Listen & Approve',
        type: 'review',
        description: 'Listen to the full episode and clips, approve or request re-generation',
        automated: false,
      },
      {
        id: 'podcast-publish',
        name: 'Spotify + YouTube Shorts',
        type: 'publish',
        description: 'Publish full episode to Spotify and clips as YouTube Shorts',
        automated: true,
      },
    ],
    keyTools: ['Claude', 'ElevenLabs', 'FFmpeg', 'Spotify API'],
    color: 'indigo',
  },
  {
    slug: 'infographic-factory',
    name: 'Infographic & Carousel Factory',
    icon: 'LayoutGrid',
    description:
      'Transforms data and insights into visually compelling carousels and infographics, producing daily visual content for Instagram and LinkedIn.',
    automationLevel: 'high',
    outputVolume: '1 carousel/day',
    schedule: '0 9 * * *',
    pillarSlugs: [
      'breaking-ai-news',
      'reshared-posts',
      'strategy-career',
      'live-demos',
      'hype-detector',
      'inside-the-machine',
      'failure-lab',
    ],
    steps: [
      {
        id: 'infographic-ingest',
        name: 'Data Source',
        type: 'ingest',
        description: 'Pull data points and insights from recent content and external sources',
        automated: true,
      },
      {
        id: 'infographic-generate',
        name: '7 Key Insights',
        type: 'generate',
        description: 'Distill source material into 7 key insights for carousel slides',
        automated: true,
      },
      {
        id: 'infographic-carousel',
        name: 'Canva Carousel',
        type: 'visual',
        description: 'Generate carousel slides using Canva API with branded templates',
        automated: true,
      },
      {
        id: 'infographic-hero',
        name: 'Hero Image',
        type: 'visual',
        description: 'Create an eye-catching hero/cover image for the carousel',
        automated: true,
      },
      {
        id: 'infographic-review',
        name: 'Visual Check',
        type: 'review',
        description: 'Review visual quality, brand consistency, and content accuracy',
        automated: false,
      },
      {
        id: 'infographic-publish',
        name: 'Instagram + LinkedIn',
        type: 'publish',
        description: 'Publish carousel to Instagram and LinkedIn with optimized captions',
        automated: true,
      },
    ],
    keyTools: ['Claude', 'Canva API', 'Buffer'],
    color: 'orange',
  },
  {
    slug: 'digital-twin',
    name: 'Digital Twin Avatar',
    icon: 'UserCircle',
    description:
      'Creates daily short-form video content using an AI-generated avatar, from script to final video with captions, published across all platforms.',
    automationLevel: 'high',
    outputVolume: '1 video/day',
    pillarSlugs: [
      'breaking-ai-news',
      'reshared-posts',
      'strategy-career',
      'live-demos',
      'hype-detector',
      'inside-the-machine',
      'failure-lab',
    ],
    steps: [
      {
        id: 'twin-generate',
        name: '60s Script',
        type: 'generate',
        description: 'Generate a compelling 60-second video script with hook and CTA',
        automated: true,
      },
      {
        id: 'twin-avatar',
        name: 'HeyGen Avatar',
        type: 'audio_video',
        description: 'Generate video using HeyGen digital twin avatar',
        automated: true,
      },
      {
        id: 'twin-captions',
        name: 'Captions',
        type: 'audio_video',
        description: 'Auto-generate and burn in captions/subtitles',
        automated: true,
      },
      {
        id: 'twin-review',
        name: 'Watch & Approve',
        type: 'review',
        description: 'Watch the generated video and approve or request changes',
        automated: false,
      },
      {
        id: 'twin-publish',
        name: 'All Platforms',
        type: 'publish',
        description: 'Publish to LinkedIn, Instagram Reels, YouTube Shorts, and Twitter',
        automated: true,
      },
    ],
    keyTools: ['Claude', 'HeyGen', 'FFmpeg', 'Buffer'],
    color: 'pink',
  },
];

export const PIPELINE_MAP = new Map(PIPELINES.map((p) => [p.slug, p]));

export function getPipeline(slug: string): PipelineConfig | undefined {
  return PIPELINE_MAP.get(slug);
}
